name: Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Build and Upload Release
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Executable
        run: |
          gcc typing_test.c -o typing_game.exe

      - name: Upload Binaries to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: typing_game.exe
          asset_name: typing_gam.exe
          tag: ${{ github.ref }}
          overwrite: true
